apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rails-policy
spec:
  podSelector:
    matchLabels:
      role: rails
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except: 
        - (laip)/32
    ports:
    - protocol: TCP
      ports: 5432
    - protocol: TCP
      port: 6379
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sidekiq-policy
spec:
  podSelector:
    matchLabels:
      role: sidekiq
  policyTypes:
  - Ingress
  - Egress
  ingress: []
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except: 93.84.132.36/32
    ports:
    - protocol: TCP
      port: 6379
